
##############
### CONFIG ###
##############

splash = false

#################
### WALLPAPER ###
#################

$current_wallpaper = /home/limones/wallpapers/giyuu_tomioka.jpg

wallpaper {
  monitor = 
  path = $current_wallpaper
}
