#################
### Variables ###
#################

source = ./variables.conf

##############
### Config ###
##############

splash = false

#################
### Wallpaper ###
#################

wallpaper {
  monitor = 
  path = $current_wallpaper
}
