#################
### Variables ###
#################

source = ./variables.conf

##############
### Config ###
##############

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    bezier = itchyFadeIn, 0.05, 0.7, 0.9, 1.0
    bezier = dayumFadeOut, 0.05, 0.7, 0.55, 1
    animation = fadeIn, 1, 5, itchyFadeIn
    animation = fadeOut, 1, 5, dayumFadeOut
    animation = inputFieldColors, 1, 3.5, linear
    animation = inputFieldDots, 1, 2, linear
}

###################
### Lock screen ###
###################

background {
    monitor =
    path = $current_wallpaper
    blur_passes = 3
    brightness = 0.4
}

# Date
label {
    monitor = 
    
    # format date according to brazilian or american letters depending on $LANG, with a neutral fallback
    text = cmd[update:0:1] echo "<span letter_spacing='144'>$(if [[ $LANG == pt_BR.UTF-8 ]]; then \
           echo "<span text_transform='capitalize'>$(date +%A)</span>, $(date +'%d de %B de %Y')"; \
           elif [[ $LANG == en_US.UTF-8 ]]; then \
           echo "$(date +'%A, %B %d, %Y')"; \
           else echo $(date +'%A, %d %B %Y'); fi)</span>"
    text_align = center
    color = $text
    font_size = 24
    font_family = $ui_font ExtraLight

    position = 0, 38.5% 
    halign = center
    valign = center
}

# Time
label {
    monitor = 
    
    text = $TIME
    text_align = center
    color = $text
    font_size = 104
    font_family = $ui_font SemiBold

    position = 0, 29.5%
    halign = center
    valign = center
}

# Avatar
image {
    monitor = 

    path = ~/.face.icon
    size = 150
    rounding = -1

    border_size = 2
    border_color = rgba(0, 0, 0, 0)

    shadow_passes = 1

    position = 0, -25.125%
    halign = center
    valign = center
}

# Locked user
label {
    monitor = 

    text = $DESC<br/><span size='12pt'>$USER</span>
    text_align = center
    color = $text
    font_size = 18
    font_family = $ui_font

    shadow_passes = 1

    position = 0, -35.5%
    halign = center
    valign = center
}

# Password input
input-field {
    monitor =
    size = 18%, 4.5%
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.29
    dots_center = true

    outer_color = rgba($lavenderAlphaff)
    inner_color = rgba($baseAlphaff)
    check_color = rgba($yellowAlphaff)
    fail_color = rgba($redAlphaff)
    font_color = rgba($textAlphaff)

    font_family = $input_font
    fade_on_empty = false
    placeholder_text = 
    rounding = 20
    fail_text = $FAIL

    capslock_color = $teal
    numlock_color = $peach
    bothlock_color = $red
    invert_numlock = true

    shadow_passes = 1

    position = 0, -41.5%
    halign = center
    valign = center
}

# Session locked
label {
    monitor =

    # translate to portuguese or english according to $LANG
    text = cmd[update:0:1] echo "$(if [[ $LANG == pt_BR.UTF-8 ]]; then \
           echo "Sessão bloqueada"; \
           else echo "Session locked"; fi)"
    text_align = center
    color = $text
    font_size = 14
    font_family = $ui_font Light

    shadow_passes = 1
    
    position = 0, -46%
    halign = center
    valign = center
}
