#################
### Variables ###
################

source = ./variables.conf

##############
### Config ###
##############

general {
  lock_cmd = pidof $session_locker || $session_locker
  unlock_cmd = pkill -USR1 $session_locker
  
  before_sleep_cmd = $session_locker
  inhibit_sleep = 2
}

#################
### Listeners ###
#################

listener {
  timeout = 290  # 4 min 50 sec
  on-timeout = notify-send -u low -a Hypridle Hypridle \
               "$(if [[ $LANG == pt_BR.UTF-8 ]]; then echo "Entrando em inatividade... Até mais!"; \
               else echo "Going idle... See you soon!"; fi)"
  on-resume = notify-send -u low -a Hypridle Hypridle \
              "$(if [[ $LANG == pt_BR.UTF-8 ]]; then echo "Bem-vindo de volta!"; \
               else echo "Welcome back!"; fi)"
}

listener {
  timeout = 300  # 5 min
  on-timeout = loginctl lock-session && sleep 1 && hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

listener {
  timeout = 310  # 5 min 10 sec
  on-timeout = [[ $(cat $sysfs_bat0/status) == Discharging ]] && hyprctl dispatch dpms on && sleep 1 && systemctl suspend
}
