####################
### Theme colors ###
####################

source = ./catppuccin-macchiato.conf

#################
### Variables ###
#################

$ui_font = Inter
$input_font = Monospace

$current_wallpaper = ~/wallpapers/giyuu_tomioka.jpg #spiderman_falling.jpg
$face_icon = ~/.face.icon

$sysfs_bat0 = /sys/class/power_supply/BAT0

$terminal = ghostty
$terminal_launch_args = +new-window
$polkit_agent = /usr/lib/hyprpolkitagent/hyprpolkitagent
$notification_daemon = mako
$imf = fcitx5 -rd
$clipboard_manager = clipse -listen
$wallpaper = hyprpaper
$sunset = hyprsunset
$session_locker = hyprlock
$idle = hypridle
