[global]

# Name of the device on Spotify Connect
device_name = "LimaPC"

# Displayed device type on other Spotify clients
device_type = "computer"

# Enable MPRIS
use_mpris = true

# Use session Dbus
dbus_type = "session"

# Set fixed zeroconf port
zeroconf_port = 1024

# Use pulseaudio as backend
backend = "pulseaudio"

# Set volume on startup
initial_volume = 60

# Disable volume normalisation
volume_normalisation = false

# Set the maximum bitrate
bitrate = 320

# Play more music after the playbar ended
autoplay = true
